### ISSUE TITLE
Conventions

### ISSUE THREAD

**Issue by Jamalam360** [FoundationGames/Improperties-Specification#1]
Yes hello I enjoy this thing that resulted from a shitpost...

While 'key=value, key = value, key= value, and key =value are all valid ways to notate that the string key may result in the string value', shouldn't there be some kind of conventions on which to use for the best readability etc.?

**Comment by ImperatorStorm** [comment]
hmm

I like `key = value` due to enhanced readability, but `key=value` is much more compressed while still being readable

**Comment by Jamalam360** [comment]
Does everyone agree that key= value and key =value is just wrong on so many levels?

**Comment by ImperatorStorm** [comment]
agree

**Comment by Jamalam360** [comment]
i'm cleaning up my issue list so goodbye issue :crab:
